username: "Admin"
password: "admin123"
url: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
username_locator: "username"
password_locator: "password"
login_button_locator: '//*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'

admin_locator: '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a/span'
